# Generated by Django 4.0.5 on 2022-09-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0010_driver_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver_reg',
        ),
    ]
