# Generated by Django 4.0.5 on 2022-09-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0019_trip_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_request',
            old_name='no_of_persons',
            new_name='no_of_person',
        ),
        migrations.RemoveField(
            model_name='trip_request',
            name='company',
        ),
    ]
