# Generated by Django 4.0.5 on 2022-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0021_driver_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_request',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
