# Generated by Django 4.0.5 on 2022-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0022_trip_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_request',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
