# Generated by Django 4.0.5 on 2022-09-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0024_rename_dob_add_driver_dateob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_driver',
            old_name='carname',
            new_name='license_no',
        ),
        migrations.RenameField(
            model_name='driver_reg',
            old_name='carname',
            new_name='license_no',
        ),
        migrations.RemoveField(
            model_name='add_driver',
            name='cartype',
        ),
        migrations.RemoveField(
            model_name='add_driver',
            name='plateno',
        ),
        migrations.RemoveField(
            model_name='driver_reg',
            name='cartype',
        ),
        migrations.RemoveField(
            model_name='driver_reg',
            name='plateno',
        ),
    ]
