# Generated by Django 4.0.5 on 2022-09-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0026_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
