# Generated by Django 4.0.5 on 2022-10-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0028_driver_add_delete_add_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('compl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.trip_request')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.comp_reg')),
                ('drv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.driver_reg')),
            ],
        ),
    ]
