# Generated by Django 4.0.5 on 2022-10-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0030_rename_compl_assign_driver_trip_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_driver',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.comp_reg'),
        ),
    ]
