# Generated by Django 4.0.5 on 2022-10-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0031_assign_driver_comp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assign_Driver',
        ),
    ]
