# Generated by Django 4.0.5 on 2022-10-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0032_delete_assign_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='driver_add',
        ),
    ]
