# Generated by Django 4.0.5 on 2022-10-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0036_user_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_feedback',
        ),
    ]
