# Generated by Django 4.0.5 on 2022-10-09 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gobetween_app', '0038_user_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_feedback',
            new_name='u_feedback',
        ),
    ]
