# Generated by Django 4.0.5 on 2022-10-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gobetween_app', '0042_remove_add_vehicle_user_remove_driver_reg_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
