# Generated by Django 4.0.5 on 2022-10-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0044_location_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_add',
            name='user',
        ),
    ]
