# Generated by Django 4.0.5 on 2022-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0047_remove_assign_trip_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
