# Generated by Django 4.0.5 on 2022-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0049_add_vehicle_veh_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='veh_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
