# Generated by Django 4.0.5 on 2022-10-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0050_alter_add_vehicle_veh_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='veh_type',
            new_name='vehtype',
        ),
    ]
