# Generated by Django 4.0.5 on 2022-10-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0051_rename_veh_type_add_vehicle_vehtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.comp_reg')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.driver_reg')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.trip_request')),
                ('veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.add_vehicle')),
            ],
        ),
    ]
