# Generated by Django 4.0.5 on 2022-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0052_schedule_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_request',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip_request',
            name='trip_amt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
