# Generated by Django 4.0.5 on 2022-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0053_trip_request_payment_status_trip_request_trip_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_request',
            name='trip_amt',
        ),
        migrations.AddField(
            model_name='assign_trip',
            name='trip_amt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
