# Generated by Django 4.0.5 on 2022-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0054_remove_trip_request_trip_amt_assign_trip_trip_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_request',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='assign_trip',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
