# Generated by Django 4.0.5 on 2022-10-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0055_remove_trip_request_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_request',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
