# Generated by Django 4.0.5 on 2022-10-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0056_trip_request_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_trip',
            name='payment',
        ),
    ]
