# Generated by Django 4.0.5 on 2022-10-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0057_remove_assign_trip_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_reg',
            name='company_name',
        ),
    ]
