# Generated by Django 4.0.5 on 2022-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0059_trip_request_purpose_delete_schedule_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_request',
            name='purpose',
        ),
    ]
