# Generated by Django 4.0.5 on 2022-10-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0061_schedule_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule_trip',
        ),
    ]
