# Generated by Django 4.0.5 on 2022-10-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0063_trip_request_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_request',
            name='purpose',
        ),
    ]
