# Generated by Django 4.0.5 on 2022-10-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0065_trip_request_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_trip',
            name='kms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
