# Generated by Django 4.0.5 on 2022-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0066_assign_trip_kms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_trip',
            old_name='trip_amt',
            new_name='km_per_amt',
        ),
        migrations.AddField(
            model_name='assign_trip',
            name='total_amt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
