# Generated by Django 4.0.5 on 2022-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0067_rename_trip_amt_assign_trip_km_per_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_trip',
            name='km_per_amt',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assign_trip',
            name='kms',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
