# Generated by Django 4.1.5 on 2023-03-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gobetween_app', '0068_alter_assign_trip_km_per_amt_alter_assign_trip_kms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('feedback', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='d_feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='u_feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='c_feedback',
        ),
        migrations.DeleteModel(
            name='d_feedback',
        ),
        migrations.DeleteModel(
            name='u_feedback',
        ),
    ]
