# Generated by Django 4.1.5 on 2023-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0069_feedback_remove_d_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
