# Generated by Django 4.1.5 on 2023-03-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0070_driver_reg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_request',
            name='user',
        ),
        migrations.AddField(
            model_name='driver_request',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.comp_reg'),
        ),
    ]
