# Generated by Django 4.1.5 on 2023-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0072_driver_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
