# Generated by Django 4.1.5 on 2023-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0073_add_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_reg',
            name='reject_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
