# Generated by Django 4.1.5 on 2023-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0074_comp_reg_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='reject_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='reject_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
