# Generated by Django 4.2 on 2023-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0075_driver_reg_reject_reason_user_reg_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_reg',
            name='upi_qrcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
