# Generated by Django 4.2 on 2023-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0076_comp_reg_upi_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='insurace_no',
            new_name='insurance_no',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='insurance_exp',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='rc_exp',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
