# Generated by Django 4.2 on 2023-04-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0077_rename_insurace_no_add_vehicle_insurance_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_request',
            name='status1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
