# Generated by Django 4.2 on 2023-04-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0078_driver_request_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_request',
            name='status1',
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='status1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
