# Generated by Django 4.2 on 2023-04-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0079_remove_driver_request_status1_driver_reg_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_request',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.driver_reg'),
        ),
    ]
