# Generated by Django 4.2 on 2023-04-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0081_add_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_trip',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.comp_reg'),
        ),
    ]
