# Generated by Django 4.2 on 2023-04-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0082_alter_assign_trip_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_request',
            name='age',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='driving_exp',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='place',
        ),
        migrations.RemoveField(
            model_name='driver_request',
            name='user',
        ),
        migrations.AddField(
            model_name='driver_request',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gobetween_app.driver_reg'),
        ),
    ]
