# Generated by Django 4.2 on 2023-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0084_driver_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_leave',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
