# Generated by Django 4.2 on 2023-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0085_driver_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='driving_experience',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='photo',
            field=models.ImageField(null=True, upload_to='driver_images/'),
        ),
    ]
