# Generated by Django 4.2 on 2023-04-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0086_driver_reg_driving_experience_driver_reg_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
