# Generated by Django 4.2 on 2023-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobetween_app', '0088_complaint_email_complaint_name_feedback_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='qrcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
